//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<System.DateTime> LastUpdateTimeStamp { get; set; }
    }
}
